name: Test

on:
  push:

jobs:
  nbb-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate logseq graph
        uses: logseq-cldwalker/graph-validator@with-composite
        with:
          directory: '..'
