name: Test

on:
  push:

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: script/yarn.lock

      - name: Fetch yarn deps
        run: cd script && yarn install --immutable

      - name: Run nbb tests
        run: cd script && yarn test
